# This is a basic workflow to help you get started with Actions

name: Run Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "30 16 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    -  name: Setup Python
       uses: actions/setup-python@v1
       with:
         python--version: 3.8 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
        && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
        && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
        && cd /tmp \
        && unzip chromedriver_linux64.zip \
        && rm -rf chromedriver_linux64.zip \
        && sudo mv chromedriver /usr/local/bin/chromedriver \
        && sudo chmod +x /usr/local/bin/chromedriver \
        && chromedriver --version 
      
    - name: Environment
      uses: ./
      with:
        working-directory: tests/
        browser: chrome
        headless: true
        
    - name: Test with pytest 
      run: python -m pytest -k test_codecademy.py --browser headless-chrome

      
        
         
